Repository Hoya-kim/elite-king-board, pull requests merged in 2022-02, with the labels that each got.

#11 feat(#6): 안드로이드 세팅
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/example/elitekingboard/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/elitekingboard/MainActivity.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: enhancement

#19 Vue Project Setup
  front/.eslintrc.json
  front/.gitkeep
  front/README.md
  front/babel.config.js
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.vue
  front/src/assets/logo.png
  front/src/assets/logo.svg
  front/src/components/HelloWorld.vue
  front/src/main.js
  front/src/plugins/vuetify.js
  front/src/plugins/webfontloader.js
  front/vue.config.js
Labels: enhancement

#23 상태관리를 위한 Vuex 모듈화 추가 - front
  front/package-lock.json
  front/package.json
  front/src/main.js
  front/src/store/articles/actions.js
  front/src/store/articles/index.js
  front/src/store/articles/mutations.js
  front/src/store/articles/state.js
  front/src/store/articles/types.js
  front/src/store/index.js
Labels: enhancement, Front-End

#24 Feature/#10 signup
  .gitignore
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/board/server/ServerApplication.java
  server/src/main/java/com/board/server/config/AppConfig.java
  server/src/main/java/com/board/server/config/AppProperties.java
  server/src/main/java/com/board/server/config/CacheConfig.java
  server/src/main/java/com/board/server/config/SecurityConfig.java
  server/src/main/java/com/board/server/infra/mail/ConsoleEmailService.java
  server/src/main/java/com/board/server/infra/mail/EmailMessage.java
  server/src/main/java/com/board/server/infra/mail/EmailService.java
  server/src/main/java/com/board/server/infra/mail/HtmlEmailService.java
  server/src/main/java/com/board/server/modules/member/Account.java
  server/src/main/java/com/board/server/modules/member/AccountController.java
  server/src/main/java/com/board/server/modules/member/AccountRepository.java
  server/src/main/java/com/board/server/modules/member/AccountService.java
  server/src/main/java/com/board/server/modules/member/Role.java
  server/src/main/java/com/board/server/modules/member/dto/SignUpRequestDto.java
  server/src/main/java/com/board/server/modules/member/dto/SignUpResponseDto.java
  server/src/main/java/com/board/server/modules/member/mapper/AccountMapper.java
  server/src/main/resources/application.properties
  server/src/main/resources/templates/error/5xx.html
  server/src/main/resources/templates/mail/authentication.html
  server/src/test/java/com/board/server/modules/member/AccountControllerTest.java
  server/src/test/java/com/board/server/modules/member/AccountRepositoryTest.java
  server/src/test/java/com/board/server/modules/member/AccountServiceTest.java
  server/src/test/resources/application.properties
Labels: enhancement, Back-End

#32 Feature/#27 sign up validation exception
  server/src/main/java/com/board/server/ServerApplication.java
  server/src/main/java/com/board/server/config/CacheConfig.java
  server/src/main/java/com/board/server/exception/InvalidSignUpRequestException.java
  server/src/main/java/com/board/server/modules/member/Account.java
  server/src/main/java/com/board/server/modules/member/AccountController.java
  server/src/main/java/com/board/server/modules/member/AccountRepository.java
  server/src/main/java/com/board/server/modules/member/AccountService.java
  server/src/main/java/com/board/server/modules/member/validator/SignUpValidator.java
  server/src/main/resources/application.properties
  server/src/test/java/com/board/server/modules/member/AccountControllerIntegrationTest.java
  server/src/test/java/com/board/server/modules/member/AccountControllerTest.java
  server/src/test/java/com/board/server/modules/member/AccountRepositoryTest.java
Labels: enhancement, Back-End

#37 Feature/#9 articles-comments
  server/build.gradle
  server/src/main/java/board/api/common/PageResponseData.java
  server/src/main/java/board/api/common/PageUtils.java
  server/src/main/java/board/api/common/PagingResponseDto.java
  server/src/main/java/board/api/config/AppConfig.java
  server/src/main/java/board/api/modules/article_comments/ArticleComment.java
  server/src/main/java/board/api/modules/article_comments/ArticleCommentController.java
  server/src/main/java/board/api/modules/article_comments/ArticleCommentRepository.java
  server/src/main/java/board/api/modules/article_comments/ArticleCommentService.java
  server/src/main/java/board/api/modules/article_comments/dto/ArticleCommentRequestDto.java
  server/src/main/java/board/api/modules/article_comments/dto/ArticleCommentResponseDto.java
Labels: enhancement, Back-End

#39 Feature/#8 article api
  server/src/main/java/board/api/config/SecurityConfig.java
  server/src/main/java/board/api/modules/account/AccountRepository.java
  server/src/main/java/board/api/modules/account/dto/SignUpRequestDto.java
  server/src/main/java/board/api/modules/articles/ArticleController.java
  server/src/main/java/board/api/modules/articles/dto/ArticleDto.java
  server/src/main/java/board/api/modules/articles/dto/CreateArticleRequest.java
  server/src/main/java/board/api/modules/articles/dto/CreateArticleResponse.java
  server/src/main/java/board/api/modules/articles/dto/GetAricleResponse.java
  server/src/main/java/board/api/modules/articles/dto/Result.java
  server/src/main/java/board/api/modules/articles/dto/UpdateArticleRequest.java
  server/src/main/java/board/api/modules/articles/dto/UpdateArticleResponse.java
  server/src/main/java/board/api/modules/articles/model/Article.java
  server/src/main/java/board/api/modules/articles/model/BaseEntity.java
  server/src/main/java/board/api/modules/articles/repository/ArticleRepository.java
  server/src/main/java/board/api/modules/articles/service/ArticleService.java
  server/src/main/resources/application.properties
  server/src/test/java/board/api/AccountControllerIntegrationTest.java
  server/src/test/java/board/api/AccountControllerTest.java
  server/src/test/java/board/api/AccountRepositoryTest.java
  server/src/test/java/board/api/AccountServiceTest.java
Labels: enhancement, Back-End

#38 Feature/#33 login
  server/build.gradle
  server/src/main/java/board/api/authentication/JwtAuthenticationFilter.java
  server/src/main/java/board/api/authentication/JwtAuthorizationFilter.java
  server/src/main/java/board/api/authentication/JwtProperties.java
  server/src/main/java/board/api/authentication/UserAccount.java
  server/src/main/java/board/api/config/CacheConfig.java
  server/src/main/java/board/api/config/CorsConfig.java
  server/src/main/java/board/api/config/SecurityConfig.java
  server/src/main/java/board/api/infra/mail/HtmlEmailService.java
  server/src/main/java/board/api/modules/account/Account.java
  server/src/main/java/board/api/modules/account/AccountController.java
  server/src/main/java/board/api/modules/account/AccountRepository.java
  server/src/main/java/board/api/modules/account/AccountService.java
  server/src/main/java/board/api/modules/articles/model/Article.java
  server/src/main/java/board/api/utils/RequestUtils.java
  server/src/main/resources/application.properties
  server/src/main/resources/templates/index.html
  server/src/test/java/board/api/modules/account/AccountControllerIntegrationTest.java
  server/src/test/java/board/api/modules/account/AccountControllerTest.java
  server/src/test/java/board/api/modules/account/AccountRepositoryTest.java
  server/src/test/java/board/api/modules/account/AccountServiceTest.java
  server/src/test/resources/application.properties
Labels: enhancement, Back-End

#40 feat(#31): Implement base layout
  front/package-lock.json
  front/package.json
  front/public/index.html
  front/src/App.vue
  front/src/assets/logo_variation_black.png
  front/src/assets/logo_variation_black.svg
  front/src/components/ArticleCard.vue
  front/src/components/ArticleModal.vue
  front/src/components/CardsContainer.vue
  front/src/components/Header.vue
  front/src/components/HelloWorld.vue
  front/src/components/SignInModal.vue
  front/src/plugins/vuetify.js
Labels: enhancement, Front-End

#43 feat(#41): EmailService real 프로퍼티에서 동작하도록 추가
  server/src/main/java/board/api/config/SecurityConfig.java
  server/src/main/java/board/api/infra/mail/HtmlEmailService.java
  server/src/main/java/board/api/modules/articles/model/Article.java
  server/src/main/resources/application.properties
Labels: bug, enhancement, Back-End

#46 feat(#45): Login Respinse에 닉네임 추가
  server/src/main/java/board/api/authentication/JwtAuthenticationFilter.java
Labels: enhancement, Back-End

#49 feat(#47): Login Response에 accountId 추가
  server/src/main/java/board/api/authentication/JwtAuthenticationFilter.java
Labels: enhancement, Back-End

#56 fix(#53): 게시글의 내용이 업데이트가 되지 않는 현상 수정
  server/src/main/java/board/api/modules/articles/ArticleController.java
  server/src/main/java/board/api/modules/articles/service/ArticleService.java
Labels: bug, Back-End

#61 remove(#59): 인증 제거
  server/src/main/java/board/api/config/SecurityConfig.java
Labels: Back-End
